<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>Introduction</title>

<script type="text/javascript">
window.onload = function() {
  var imgs = document.getElementsByTagName('img'), i, img;
  for (i = 0; i < imgs.length; i++) {
    img = imgs[i];
    // center an image if it is the only element of its parent
    if (img.parentElement.childElementCount === 1)
      img.parentElement.style.textAlign = 'center';
  }
};
</script>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: #990073
   }

   pre .number {
     color: #099;
   }

   pre .comment {
     color: #998;
     font-style: italic
   }

   pre .keyword {
     color: #900;
     font-weight: bold
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: #d14;
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>



<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 13px;
}

body {
  max-width: 800px;
  margin: auto;
  padding: 1em;
  line-height: 20px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 {
   font-size:2.2em;
}

h2 {
   font-size:1.8em;
}

h3 {
   font-size:1.4em;
}

h4 {
   font-size:1.0em;
}

h5 {
   font-size:0.9em;
}

h6 {
   font-size:0.8em;
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre, img {
  max-width: 100%;
}
pre {
  overflow-x: auto;
}
pre code {
   display: block; padding: 0.5em;
}

code {
  font-size: 92%;
  border: 1px solid #ccc;
}

code[class] {
  background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * {
      background: transparent !important;
      color: black !important;
      filter:none !important;
      -ms-filter: none !important;
   }

   body {
      font-size:12pt;
      max-width:100%;
   }

   a, a:visited {
      text-decoration: underline;
   }

   hr {
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote {
      padding-right: 1em;
      page-break-inside: avoid;
   }

   tr, img {
      page-break-inside: avoid;
   }

   img {
      max-width: 100% !important;
   }

   @page :left {
      margin: 15mm 20mm 15mm 10mm;
   }

   @page :right {
      margin: 15mm 10mm 15mm 20mm;
   }

   p, h2, h3 {
      orphans: 3; widows: 3;
   }

   h2, h3 {
      page-break-after: avoid;
   }
}
</style>



</head>

<body>
<h2>Introduction</h2>

<h2>How to use the <code>qgcomp</code> package</h2>

<h3>Example 1</h3>

<table><thead>
<tr>
<th align="right">y</th>
<th align="right">disease_state</th>
<th align="right">sex</th>
<th align="right">log_LBX074LA</th>
<th align="right">log_LBX099LA</th>
<th align="right">log_LBX105LA</th>
<th align="right">log_LBX118LA</th>
<th align="right">log_LBX138LA</th>
<th align="right">log_LBX153LA</th>
<th align="right">log_LBX156LA</th>
<th align="right">log_LBX157LA</th>
<th align="right">log_LBX167LA</th>
<th align="right">log_LBX170LA</th>
<th align="right">log_LBX180LA</th>
<th align="right">log_LBX187LA</th>
<th align="right">log_LBX189LA</th>
<th align="right">log_LBX194LA</th>
<th align="right">log_LBX196LA</th>
<th align="right">log_LBX199LA</th>
<th align="right">log_LBXD01LA</th>
<th align="right">log_LBXD02LA</th>
<th align="right">log_LBXD03LA</th>
<th align="right">log_LBXD04LA</th>
<th align="right">log_LBXD05LA</th>
<th align="right">log_LBXD07LA</th>
<th align="right">log_LBXF01LA</th>
<th align="right">log_LBXF02LA</th>
<th align="right">log_LBXF03LA</th>
<th align="right">log_LBXF04LA</th>
<th align="right">log_LBXF05LA</th>
<th align="right">log_LBXF06LA</th>
<th align="right">log_LBXF07LA</th>
<th align="right">log_LBXF08LA</th>
<th align="right">log_LBXF09LA</th>
<th align="right">log_LBXPCBLA</th>
<th align="right">log_LBXTCDLA</th>
<th align="right">log_LBXHXCLA</th>
</tr>
</thead><tbody>
<tr>
<td align="right">-0.4224332</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0.0680716</td>
<td align="right">-0.1608614</td>
<td align="right">0.9648013</td>
<td align="right">-0.1815684</td>
<td align="right">0.7506797</td>
<td align="right">0.9363278</td>
<td align="right">-0.0364088</td>
<td align="right">0.1971499</td>
<td align="right">1.1192873</td>
<td align="right">0.2972489</td>
<td align="right">0.1920384</td>
<td align="right">-0.5257044</td>
<td align="right">-0.1659253</td>
<td align="right">0.4017490</td>
<td align="right">-0.0143133</td>
<td align="right">0.8692975</td>
<td align="right">0.0846309</td>
<td align="right">0.0012511</td>
<td align="right">-0.2847784</td>
<td align="right">0.6327454</td>
<td align="right">0.4078422</td>
<td align="right">0.1661874</td>
<td align="right">-1.2905580</td>
<td align="right">-1.0359049</td>
<td align="right">1.6893966</td>
<td align="right">-0.1942655</td>
<td align="right">0.4322813</td>
<td align="right">-1.8049708</td>
<td align="right">-0.7816081</td>
<td align="right">0.2459645</td>
<td align="right">-1.0917383</td>
<td align="right">-0.3476487</td>
<td align="right">-0.0358878</td>
<td align="right">1.2711118</td>
</tr>
<tr>
<td align="right">0.7613784</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.5276676</td>
<td align="right">1.4403102</td>
<td align="right">0.7753093</td>
<td align="right">0.1055764</td>
<td align="right">-0.9015101</td>
<td align="right">0.1677693</td>
<td align="right">0.7643587</td>
<td align="right">-0.6001477</td>
<td align="right">0.6175614</td>
<td align="right">-0.3577213</td>
<td align="right">0.2879546</td>
<td align="right">-0.1557095</td>
<td align="right">-0.6755189</td>
<td align="right">0.0519114</td>
<td align="right">0.3351334</td>
<td align="right">-1.1385368</td>
<td align="right">0.5852100</td>
<td align="right">-1.4539998</td>
<td align="right">1.1116691</td>
<td align="right">0.0767604</td>
<td align="right">-0.0295292</td>
<td align="right">-1.2578515</td>
<td align="right">-0.0246641</td>
<td align="right">0.5600564</td>
<td align="right">0.1143720</td>
<td align="right">1.1365974</td>
<td align="right">0.8777775</td>
<td align="right">-0.1214907</td>
<td align="right">0.7902525</td>
<td align="right">0.2255480</td>
<td align="right">-1.0510728</td>
<td align="right">0.5891812</td>
<td align="right">-0.6304355</td>
<td align="right">0.7265865</td>
</tr>
<tr>
<td align="right">-2.1113324</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">-1.8650139</td>
<td align="right">1.4885628</td>
<td align="right">-1.5420050</td>
<td align="right">-0.5412270</td>
<td align="right">-1.3624492</td>
<td align="right">-0.4177779</td>
<td align="right">0.1414001</td>
<td align="right">0.1333590</td>
<td align="right">-0.9901708</td>
<td align="right">0.1024100</td>
<td align="right">-0.0622932</td>
<td align="right">1.0824292</td>
<td align="right">-0.6920183</td>
<td align="right">-1.7204760</td>
<td align="right">-1.2079225</td>
<td align="right">0.3543356</td>
<td align="right">-0.8116185</td>
<td align="right">-0.8790250</td>
<td align="right">0.4616429</td>
<td align="right">-2.0101411</td>
<td align="right">-1.2859585</td>
<td align="right">0.8281122</td>
<td align="right">0.0921212</td>
<td align="right">-0.6980090</td>
<td align="right">0.2987547</td>
<td align="right">-0.0450820</td>
<td align="right">0.4917081</td>
<td align="right">0.3754392</td>
<td align="right">-1.6193861</td>
<td align="right">0.0812163</td>
<td align="right">0.2236327</td>
<td align="right">-0.5211774</td>
<td align="right">-1.0174183</td>
<td align="right">-0.4092153</td>
</tr>
<tr>
<td align="right">2.2222394</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1.2585209</td>
<td align="right">1.6110700</td>
<td align="right">2.2069536</td>
<td align="right">1.3286183</td>
<td align="right">1.8871201</td>
<td align="right">1.8393058</td>
<td align="right">2.2751535</td>
<td align="right">1.1307767</td>
<td align="right">1.2204913</td>
<td align="right">0.1958512</td>
<td align="right">0.9461497</td>
<td align="right">-0.0325942</td>
<td align="right">-0.3940764</td>
<td align="right">0.2984753</td>
<td align="right">0.7837346</td>
<td align="right">1.9352485</td>
<td align="right">0.1973576</td>
<td align="right">0.8376586</td>
<td align="right">-1.2715081</td>
<td align="right">-1.2577145</td>
<td align="right">-0.5786619</td>
<td align="right">0.6304414</td>
<td align="right">1.3148279</td>
<td align="right">0.2485757</td>
<td align="right">-0.4723713</td>
<td align="right">0.7557946</td>
<td align="right">0.3307601</td>
<td align="right">-0.0342781</td>
<td align="right">-0.2875164</td>
<td align="right">0.4176680</td>
<td align="right">0.0977815</td>
<td align="right">-1.1273511</td>
<td align="right">1.0095760</td>
<td align="right">0.6639172</td>
</tr>
<tr>
<td align="right">-0.2190805</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">-1.0138713</td>
<td align="right">-1.9903436</td>
<td align="right">-0.6009229</td>
<td align="right">-0.8907467</td>
<td align="right">-0.4789443</td>
<td align="right">-2.8190387</td>
<td align="right">-0.0095402</td>
<td align="right">-1.5477137</td>
<td align="right">0.5180853</td>
<td align="right">-2.1491031</td>
<td align="right">-2.7951863</td>
<td align="right">-1.5755779</td>
<td align="right">-0.5270997</td>
<td align="right">-0.2450904</td>
<td align="right">-1.1242993</td>
<td align="right">-0.6902691</td>
<td align="right">-0.5791061</td>
<td align="right">-1.9495504</td>
<td align="right">-1.3426006</td>
<td align="right">0.6178038</td>
<td align="right">-1.2587666</td>
<td align="right">-0.3310535</td>
<td align="right">-1.5882632</td>
<td align="right">-1.3967154</td>
<td align="right">-1.2128921</td>
<td align="right">-0.8581706</td>
<td align="right">-0.6420270</td>
<td align="right">-1.6946821</td>
<td align="right">-0.2143440</td>
<td align="right">-1.4720725</td>
<td align="right">-0.5997930</td>
<td align="right">-1.0896972</td>
<td align="right">-0.3474791</td>
<td align="right">-0.7175427</td>
</tr>
<tr>
<td align="right">-1.7282770</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">-0.9752573</td>
<td align="right">-0.6864727</td>
<td align="right">0.3389021</td>
<td align="right">0.5984246</td>
<td align="right">0.0270300</td>
<td align="right">-0.4798327</td>
<td align="right">-0.3867123</td>
<td align="right">-1.0377681</td>
<td align="right">-0.7329465</td>
<td align="right">-0.7148301</td>
<td align="right">0.4060471</td>
<td align="right">-0.5076881</td>
<td align="right">0.2215813</td>
<td align="right">0.3212146</td>
<td align="right">-0.1809994</td>
<td align="right">1.4622912</td>
<td align="right">0.0165252</td>
<td align="right">-0.6026058</td>
<td align="right">-0.0865081</td>
<td align="right">-0.7574191</td>
<td align="right">-0.0918236</td>
<td align="right">-0.3804055</td>
<td align="right">-0.0150627</td>
<td align="right">0.5944020</td>
<td align="right">0.4030363</td>
<td align="right">-0.1233755</td>
<td align="right">-0.7816779</td>
<td align="right">-0.3795485</td>
<td align="right">0.4316160</td>
<td align="right">1.7915524</td>
<td align="right">-0.9154308</td>
<td align="right">0.2882417</td>
<td align="right">0.6230951</td>
<td align="right">1.4571064</td>
</tr>
<tr>
<td align="right">0.4219639</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">-0.6225983</td>
<td align="right">1.0113598</td>
<td align="right">-0.2162429</td>
<td align="right">0.7575008</td>
<td align="right">-0.2571729</td>
<td align="right">0.9804511</td>
<td align="right">0.4458043</td>
<td align="right">1.3962681</td>
<td align="right">-0.1979610</td>
<td align="right">0.1995122</td>
<td align="right">1.4669089</td>
<td align="right">1.0634414</td>
<td align="right">0.8339600</td>
<td align="right">1.5867141</td>
<td align="right">0.7249490</td>
<td align="right">0.7584681</td>
<td align="right">0.2701363</td>
<td align="right">0.9317193</td>
<td align="right">0.0963273</td>
<td align="right">0.3944993</td>
<td align="right">0.6827900</td>
<td align="right">-0.5437556</td>
<td align="right">0.9504820</td>
<td align="right">0.5142011</td>
<td align="right">0.5474847</td>
<td align="right">0.4452620</td>
<td align="right">-0.4822166</td>
<td align="right">0.7318831</td>
<td align="right">0.0323481</td>
<td align="right">-0.9661976</td>
<td align="right">0.7297474</td>
<td align="right">-0.1620114</td>
<td align="right">0.5754746</td>
<td align="right">0.9274046</td>
</tr>
<tr>
<td align="right">-0.4762419</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">-0.1801051</td>
<td align="right">-0.5805092</td>
<td align="right">-0.8038376</td>
<td align="right">-0.7786034</td>
<td align="right">-1.5457539</td>
<td align="right">-1.3117169</td>
<td align="right">-0.9734300</td>
<td align="right">-0.0261900</td>
<td align="right">0.5308421</td>
<td align="right">-0.2485865</td>
<td align="right">0.2103118</td>
<td align="right">-0.0912344</td>
<td align="right">-0.1011264</td>
<td align="right">-0.4217051</td>
<td align="right">0.4682131</td>
<td align="right">-0.9008740</td>
<td align="right">-0.4390236</td>
<td align="right">-1.0384994</td>
<td align="right">-1.0510064</td>
<td align="right">-0.1617107</td>
<td align="right">-1.5014766</td>
<td align="right">-1.1384429</td>
<td align="right">1.7696655</td>
<td align="right">1.9844850</td>
<td align="right">-0.4584083</td>
<td align="right">-1.8996102</td>
<td align="right">-1.0736679</td>
<td align="right">1.2719959</td>
<td align="right">1.2918048</td>
<td align="right">-0.0684242</td>
<td align="right">0.4754351</td>
<td align="right">-1.0453685</td>
<td align="right">0.0445513</td>
<td align="right">-1.8944198</td>
</tr>
<tr>
<td align="right">-0.5126990</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0.4502187</td>
<td align="right">0.7892304</td>
<td align="right">0.7107290</td>
<td align="right">0.2754549</td>
<td align="right">0.0613806</td>
<td align="right">0.3399312</td>
<td align="right">1.0176518</td>
<td align="right">1.1807174</td>
<td align="right">1.2440091</td>
<td align="right">1.5589123</td>
<td align="right">-0.8405278</td>
<td align="right">-0.2002233</td>
<td align="right">0.2201809</td>
<td align="right">0.2284441</td>
<td align="right">-0.1742271</td>
<td align="right">-0.1887278</td>
<td align="right">0.3027553</td>
<td align="right">-0.3797491</td>
<td align="right">-0.4089264</td>
<td align="right">-0.5428011</td>
<td align="right">1.2964970</td>
<td align="right">-0.2374201</td>
<td align="right">0.1206623</td>
<td align="right">0.4179228</td>
<td align="right">1.3594435</td>
<td align="right">1.6920543</td>
<td align="right">-0.3431321</td>
<td align="right">-0.2684203</td>
<td align="right">0.9664860</td>
<td align="right">-0.0108648</td>
<td align="right">-0.9556556</td>
<td align="right">2.0269212</td>
<td align="right">0.0600171</td>
<td align="right">0.4541168</td>
</tr>
<tr>
<td align="right">-0.8479847</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">-0.4461221</td>
<td align="right">-1.0556249</td>
<td align="right">1.0676569</td>
<td align="right">0.0681564</td>
<td align="right">-0.9582167</td>
<td align="right">-0.3967903</td>
<td align="right">0.0196100</td>
<td align="right">0.0467119</td>
<td align="right">0.5172333</td>
<td align="right">0.2781621</td>
<td align="right">0.1674821</td>
<td align="right">1.1879319</td>
<td align="right">-1.0221745</td>
<td align="right">-1.3879976</td>
<td align="right">-0.7295127</td>
<td align="right">-1.7526492</td>
<td align="right">-0.7668207</td>
<td align="right">0.5923798</td>
<td align="right">1.0463819</td>
<td align="right">0.9856947</td>
<td align="right">-1.1673793</td>
<td align="right">-0.7855519</td>
<td align="right">-0.8638427</td>
<td align="right">-0.7379376</td>
<td align="right">-0.0984674</td>
<td align="right">-0.7446359</td>
<td align="right">-0.2253229</td>
<td align="right">-0.9085362</td>
<td align="right">-0.8710364</td>
<td align="right">1.6918778</td>
<td align="right">-0.8597897</td>
<td align="right">-0.4343029</td>
<td align="right">0.4885121</td>
<td align="right">-1.5592026</td>
</tr>
</tbody></table>

<p>qgcomp with a continuous outcome:
This script calls a wqs model for a continuous outcome using the function <code>gwqs</code>. </p>

<pre><code class="r"># we save the names of the mixture variables in the variable &quot;Xnm&quot;
data(&quot;wqs_data&quot;, package=&quot;gWQS&quot;)

Xnm = c(&quot;log_LBX074LA&quot;, &quot;log_LBX099LA&quot;, &quot;log_LBX105LA&quot;, &quot;log_LBX118LA&quot;,
&quot;log_LBX138LA&quot;, &quot;log_LBX153LA&quot;, &quot;log_LBX156LA&quot;, &quot;log_LBX157LA&quot;, &quot;log_LBX167LA&quot;,
&quot;log_LBX170LA&quot;, &quot;log_LBX180LA&quot;, &quot;log_LBX187LA&quot;, &quot;log_LBX189LA&quot;, &quot;log_LBX194LA&quot;,
&quot;log_LBX196LA&quot;, &quot;log_LBX199LA&quot;, &quot;log_LBXD01LA&quot;, &quot;log_LBXD02LA&quot;, &quot;log_LBXD03LA&quot;,
&quot;log_LBXD04LA&quot;, &quot;log_LBXD05LA&quot;, &quot;log_LBXD07LA&quot;, &quot;log_LBXF01LA&quot;, &quot;log_LBXF02LA&quot;,
&quot;log_LBXF03LA&quot;, &quot;log_LBXF04LA&quot;, &quot;log_LBXF05LA&quot;, &quot;log_LBXF06LA&quot;, &quot;log_LBXF07LA&quot;,
&quot;log_LBXF08LA&quot;, &quot;log_LBXF09LA&quot;, &quot;log_LBXPCBLA&quot;, &quot;log_LBXTCDLA&quot;, &quot;log_LBXHXCLA&quot;)


# we run the model and save the results in the variable &quot;results&quot;
results = qgcomp.noboot(y~.,dat=wqs_data[,c(Xnm, &#39;y&#39;)], family=gaussian())
</code></pre>

<p>Including all model terms as exposures of interest</p>

<pre><code class="r"># we compare...

gcompmod = qgcomp.noboot(disease_state~.,wqs_data[,c(Xnm, &#39;disease_state&#39;)], family=binomial(), q=4)
</code></pre>

<p>Including all model terms as exposures of interest</p>

<pre><code class="r">wqsmod = gwqs(disease_state ~ 1, mix_name = Xnm, data = wqs_data, q = 4, 
     validation = 0.6, b = 3, b1_pos = F, b1_constr = F, family=&#39;binomial&#39;, seed=125)
</code></pre>

<pre><code>## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function

## Warning in .safefunx(tmpv, .solnp_fun, .env, ...): 
## solnp--&gt;warning: NaN detected in function call...check your function
</code></pre>

<p>[1] &ldquo;The optimization function did not converge 0 times&rdquo;</p>

<pre><code class="r">wqsmod$final_weights
</code></pre>

<pre><code>             mix_name  mean_weight
</code></pre>

<p>log_LBXF01LA log_LBXF01LA 1.594500e-01
log_LBX167LA log_LBX167LA 1.512775e-01
log_LBX180LA log_LBX180LA 1.389033e-01
log_LBX170LA log_LBX170LA 1.293262e-01
log_LBXF04LA log_LBXF04LA 1.112770e-01
log_LBX196LA log_LBX196LA 5.989367e-02
log_LBXD02LA log_LBXD02LA 4.308660e-02
log_LBXPCBLA log_LBXPCBLA 4.238708e-02
log_LBX118LA log_LBX118LA 2.748439e-02
log_LBX189LA log_LBX189LA 2.641851e-02
log_LBXHXCLA log_LBXHXCLA 2.616894e-02
log_LBX153LA log_LBX153LA 1.611002e-02
log_LBXF02LA log_LBXF02LA 1.332884e-02
log_LBXF07LA log_LBXF07LA 1.323860e-02
log_LBXF06LA log_LBXF06LA 1.167540e-02
log_LBXD01LA log_LBXD01LA 1.165293e-02
log_LBX199LA log_LBX199LA 9.822605e-03
log_LBXD07LA log_LBXD07LA 6.926303e-03
log_LBX194LA log_LBX194LA 1.571371e-03
log_LBX138LA log_LBX138LA 2.458828e-07
log_LBXD04LA log_LBXD04LA 1.714727e-07
log_LBX099LA log_LBX099LA 6.504292e-08
log_LBX187LA log_LBX187LA 5.880036e-08
log_LBXTCDLA log_LBXTCDLA 5.419637e-08
log_LBX105LA log_LBX105LA 3.803308e-08
log_LBX156LA log_LBX156LA 3.404966e-08
log_LBX157LA log_LBX157LA 2.928430e-08
log_LBXF08LA log_LBXF08LA 2.903891e-08
log_LBXF09LA log_LBXF09LA 1.954859e-08
log_LBX074LA log_LBX074LA 1.656317e-08
log_LBXD03LA log_LBXD03LA 1.393948e-08
log_LBXF05LA log_LBXF05LA 1.106955e-08
log_LBXD05LA log_LBXD05LA 1.053564e-08
log_LBXF03LA log_LBXF03LA 8.367659e-09</p>

<pre><code class="r">summary(wqsmod$fit)
</code></pre>

<p>Call:
glm(formula = y ~ ., family = binomial(link = &ldquo;logit&rdquo;), data = new_data)</p>

<p>Deviance Residuals: 
    Min       1Q   Median       3Q      Max<br/>
-0.8938  -0.8801  -0.8741   1.5017   1.5292  </p>

<p>Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)<br/>
(Intercept) -0.80027    0.35111  -2.279   0.0227 *</p>

<h2>wqs          0.03074    0.21696   0.142   0.8873  </h2>

<p>Signif. codes:  0 &#39;<em>**&#39; 0.001 &#39;</em><em>&#39; 0.01 &#39;</em>&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</p>

<p>(Dispersion parameter for binomial family taken to be 1)</p>

<pre><code>Null deviance: 376.12  on 299  degrees of freedom
</code></pre>

<p>Residual deviance: 376.10  on 298  degrees of freedom
AIC: 380.1</p>

<p>Number of Fisher Scoring iterations: 4</p>

<pre><code class="r">gcompmod
</code></pre>

<p>Scaled effect size (positive direction, sum of positive coefficients = 1.69)
log_LBX156LA log_LBX194LA log_LBX105LA log_LBX138LA log_LBXF09LA 
    0.098960     0.094117     0.090794     0.073728     0.071542 
log_LBXHXCLA log_LBXD02LA log_LBXF08LA log_LBXD04LA log_LBXD01LA 
    0.071025     0.067497     0.066298     0.055614     0.052980 
log_LBXF05LA log_LBXPCBLA log_LBX118LA log_LBX153LA log_LBX189LA 
    0.051612     0.039568     0.037921     0.028775     0.026268 
log_LBXF01LA log_LBX157LA log_LBX180LA log_LBXF03LA log_LBXD05LA 
    0.024350     0.024323     0.013647     0.008858     0.001437 
log_LBX187LA 
    0.000685 </p>

<p>Scaled effect size (negative direction, sum of negative coefficients = -1.74)
log_LBX170LA log_LBXD07LA log_LBX199LA log_LBXF07LA log_LBX167LA 
      0.1666       0.1455       0.1442       0.1280       0.1041 
log_LBXF04LA log_LBXF06LA log_LBX099LA log_LBX196LA log_LBXF02LA 
      0.1021       0.0426       0.0406       0.0302       0.0264 
log_LBXD03LA log_LBX074LA log_LBXTCDLA 
      0.0247       0.0241       0.0210 </p>

<p>Mixture log(OR) (Delta method CI):
gamma (CI): -0.0581 (-0.472,0.356), z=-0.275, p=0.784</p>

<p>This model &hellip;</p>

<table><thead>
<tr>
<th align="right">x</th>
</tr>
</thead><tbody>
<tr>
<td align="right">0.160</td>
</tr>
<tr>
<td align="right">0.147</td>
</tr>
<tr>
<td align="right">0.124</td>
</tr>
<tr>
<td align="right">0.113</td>
</tr>
<tr>
<td align="right">0.093</td>
</tr>
<tr>
<td align="right">0.071</td>
</tr>
<tr>
<td align="right">0.057</td>
</tr>
<tr>
<td align="right">0.045</td>
</tr>
<tr>
<td align="right">0.038</td>
</tr>
<tr>
<td align="right">0.036</td>
</tr>
<tr>
<td align="right">0.035</td>
</tr>
<tr>
<td align="right">0.019</td>
</tr>
<tr>
<td align="right">0.017</td>
</tr>
<tr>
<td align="right">0.012</td>
</tr>
<tr>
<td align="right">0.010</td>
</tr>
<tr>
<td align="right">0.007</td>
</tr>
<tr>
<td align="right">0.007</td>
</tr>
<tr>
<td align="right">0.006</td>
</tr>
</tbody></table>

<table><thead>
<tr>
<th align="right">x</th>
</tr>
</thead><tbody>
<tr>
<td align="right">0.215</td>
</tr>
<tr>
<td align="right">0.141</td>
</tr>
<tr>
<td align="right">0.097</td>
</tr>
<tr>
<td align="right">0.088</td>
</tr>
<tr>
<td align="right">0.087</td>
</tr>
<tr>
<td align="right">0.068</td>
</tr>
<tr>
<td align="right">0.063</td>
</tr>
<tr>
<td align="right">0.054</td>
</tr>
<tr>
<td align="right">0.043</td>
</tr>
<tr>
<td align="right">0.040</td>
</tr>
<tr>
<td align="right">0.038</td>
</tr>
<tr>
<td align="right">0.034</td>
</tr>
<tr>
<td align="right">0.019</td>
</tr>
<tr>
<td align="right">0.005</td>
</tr>
<tr>
<td align="right">0.005</td>
</tr>
<tr>
<td align="right">0.002</td>
</tr>
</tbody></table>

<p>In the second plot&hellip;</p>

<p>To see the estimates of the mixture effect, we run the following</p>

<pre><code class="r">print(results)
</code></pre>

<p>This last table tells us&hellip;  </p>

<p>The <code>qgcomp.noboot</code> function gives back other outputs&hellip;</p>

<h3>Example 2</h3>

<p>In the following code we run a logistic regression (<code>family = &quot;binomial&quot;</code>)&hellip;</p>

<pre><code class="r">gcompmod = qgcomp.noboot(disease_state~sex+log_LBX074LA+log_LBX099LA+log_LBX105LA+log_LBX118LA+log_LBX138LA+log_LBX153LA+
                           log_LBX156LA+log_LBX157LA+log_LBX167LA+log_LBX170LA+log_LBX180LA+log_LBX187LA+log_LBX189LA+
                           log_LBX194LA+log_LBX196LA+log_LBX199LA+log_LBXD01LA+log_LBXD02LA+log_LBXD03LA+log_LBXD04LA+
                           log_LBXD05LA+log_LBXD07LA+log_LBXF01LA+log_LBXF02LA+log_LBXF03LA+log_LBXF04LA+log_LBXF05LA+
                           log_LBXF06LA+log_LBXF07LA+log_LBXF08LA+log_LBXF09LA+log_LBXPCBLA+log_LBXTCDLA+log_LBXHXCLA,
                         expnms=Xnm,
                         wqs_data[,c(Xnm, &quot;sex&quot;, &#39;disease_state&#39;)], family=binomial(), q=4)
wqsmod = gwqs(disease_state ~ sex, mix_name = Xnm, data = wqs_data, q = 4, 
     validation = 0.6, b = 3, b1_pos = F, b1_constr = F, family=&#39;binomial&#39;, seed=125)
</code></pre>

<p>[1] &ldquo;The optimization function did not converge 0 times&rdquo;</p>

<p>From the first plot we see&hellip;</p>

<pre><code class="r">print(gcompmod)
summary(gcompmod$fit)
</code></pre>

<pre><code>             mix_name  mean_weight
</code></pre>

<p>log_LBX167LA log_LBX167LA 1.773694e-01
log_LBXF01LA log_LBXF01LA 1.579708e-01
log_LBX180LA log_LBX180LA 1.408461e-01
log_LBX170LA log_LBX170LA 1.360615e-01
log_LBXF04LA log_LBXF04LA 1.153746e-01
log_LBXPCBLA log_LBXPCBLA 4.562147e-02
log_LBX196LA log_LBX196LA 4.351125e-02
log_LBXD02LA log_LBXD02LA 3.211508e-02
log_LBX118LA log_LBX118LA 3.147274e-02
log_LBXHXCLA log_LBXHXCLA 3.028686e-02
log_LBX189LA log_LBX189LA 2.805234e-02
log_LBX153LA log_LBX153LA 2.624729e-02
log_LBXF06LA log_LBXF06LA 1.656195e-02
log_LBXD01LA log_LBXD01LA 1.007162e-02
log_LBX199LA log_LBX199LA 3.430755e-03
log_LBXF02LA log_LBXF02LA 3.173771e-03
log_LBXD07LA log_LBXD07LA 1.831359e-03
log_LBX194LA log_LBX194LA 3.583818e-07
log_LBX138LA log_LBX138LA 1.417820e-07
log_LBX099LA log_LBX099LA 9.857947e-08
log_LBXF07LA log_LBXF07LA 9.418940e-08
log_LBXD04LA log_LBXD04LA 7.637178e-08
log_LBX187LA log_LBX187LA 6.021228e-08
log_LBXTCDLA log_LBXTCDLA 4.845691e-08
log_LBX156LA log_LBX156LA 4.835792e-08
log_LBXF08LA log_LBXF08LA 3.349906e-08
log_LBX105LA log_LBX105LA 3.113432e-08
log_LBX157LA log_LBX157LA 3.062864e-08
log_LBXF09LA log_LBXF09LA 2.353027e-08
log_LBX074LA log_LBX074LA 1.447614e-08
log_LBXD03LA log_LBXD03LA 1.282351e-08
log_LBXF05LA log_LBXF05LA 1.230270e-08
log_LBXF03LA log_LBXF03LA 1.102888e-08
log_LBXD05LA log_LBXD05LA 1.037097e-08</p>

<p>Call:
glm(formula = y ~ ., family = binomial(link = &ldquo;logit&rdquo;), data = new_data)</p>

<p>Deviance Residuals: 
    Min       1Q   Median       3Q      Max<br/>
-0.9532  -0.9377  -0.8148   1.4305   1.6030  </p>

<p>Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)<br/>
(Intercept) -0.96314    0.36516  -2.638  0.00835 **
wqs          0.02236    0.21507   0.104  0.91721   </p>

<h2>sex          0.34491    0.24915   1.384  0.16626   </h2>

<p>Signif. codes:  0 &#39;<em>**&#39; 0.001 &#39;</em><em>&#39; 0.01 &#39;</em>&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</p>

<p>(Dispersion parameter for binomial family taken to be 1)</p>

<pre><code>Null deviance: 376.12  on 299  degrees of freedom
</code></pre>

<p>Residual deviance: 374.16  on 297  degrees of freedom
AIC: 380.16</p>

<p>Number of Fisher Scoring iterations: 4</p>

<h2>References</h2>

<h2>Acknowledgements</h2>

<p>The development of this package was supported by NIH Grant RO1ES02953101</p>

</body>

</html>
